-- 1. Create site_settings table
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT
);

-- 2. Insert default settings (if they don't exist)
INSERT INTO site_settings (key, value)
VALUES 
  ('hero_image', 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&q=80&w=2070'),
  ('contact_phone', '99112233'),
  ('contact_name', 'ALL Catering')
ON CONFLICT (key) DO NOTHING;

-- 3. Fix Permissions (Allow Anon/Public to Update and Delete)
-- Note: In a real production app, you should restrict this to authenticated users.
-- But for this project to work easily without complex auth setup for now:

-- Enable RLS on all tables
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts (optional, but safer)
DROP POLICY IF EXISTS "Allow public access" ON orders;
DROP POLICY IF EXISTS "Allow public access" ON menu_items;
DROP POLICY IF EXISTS "Allow public access" ON site_settings;

-- Create permissive policies for ALL operations (Select, Insert, Update, Delete)
CREATE POLICY "Allow public access" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON menu_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON site_settings FOR ALL USING (true) WITH CHECK (true);
